### ISSUE TITLE
Linux preset folder

### ISSUE THREAD

**Issue by KottV** [talaviram/TICK#4]
Hi!

There are two issues actually.
TICK looks for presets in the `/opt/Tal Aviram/TICK/Presets/` folder, while TICK's deb installer puts them in the `/opt/TICK/Factory` that's why it doesn't see preset folder at the start.

In Linux using `/opt/` is very optional. The right way is to place Factory presets in the `/usr/share/TICK` (it's read-only dir for users) and use `~/.config/TICK` or `~/.local/share/TICK` for user presets. I know it could take additional work, but it will make Linux users more happy :)

**Comment by talaviram** [comment]
Thank you for the report.
I've updates the script to use `/opt/Tal Aviram/TICK/Presets/`.

About `opt` being opinionated/flavored by release.
I use a JUCE constant (https://docs.juce.com/master/classFile.html#a3e19cafabb03c5838160263a6e76313d)
So it might be nicer to update the JUCE documentation. 

Adding a different logic for factory/user is a bigger refactor. I guess next approach would be:
- allow setting different folder for presets.
- use similar approach to mobile, so when not presets folder for user is found, it'll copy the one from the `/usr/share`.

Thanks.

**Comment by KottV** [comment]
Thanks for fixing that.

According Factory presets folder you might consider make them binary resources as has been done in Odin2 https://github.com/TheWaveWarden/odin2/issues/322#issuecomment-787043857.

**Comment by talaviram** [comment]
> you might consider make them binary resources as has been done in Odin2

Actually, the factory sounds are binary resources :)
It's just the actual presets that aren't embedded into the binary. (except the default - `Tick Tock` preset)

I'm closing the specific issue. But...
feel free to open a [FR] for separating the User/Factory code.
Not sure if I'll have resources for it but as with any open-source, a PR is always welcomed :)

Thank you again for notifying about the broken path in the debian package.
