### ISSUE TITLE
macOS installer requires Rosetta

### ISSUE THREAD

**Issue by postprivee** [talaviram/TICK#5]
hi @talaviram 

TICK can not be installed on M1+M2 Macs because of Rosetta requirement - https://support.apple.com/en-us/HT211861 - 
I guess the installer is still Intel binary.

could you update the installer to universal binary?

**Comment by talaviram** [comment]
Thanks for opening this issue.

Indeed.
Though from what I understand it's not a binary but rather explicit wrong configuration in the xml of the pkg.
https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/

TICK uses [Packages](http://s.sudre.free.fr/Software/Packages/about.html).
So with upcoming build this would also be addressed as my entire build toolchain is updated.

**Comment by talaviram** [comment]
Let me know if [0.5.0](https://github.com/talaviram/TICK/releases/tag/v0.5.0) just released resolves this.

**Comment by postprivee** [comment]
@talaviram 0.5.0 requires Rosetta too

**Comment by talaviram** [comment]
Thanks. I've fixed it. so this will be reflect on next build.
