### ISSUE TITLE
Buttons or key commands to increase or decrease tempo

### ISSUE THREAD

**Issue by danryker** [talaviram/TICK#8]
I really appreciate Tick.
I would love to have buttons or key commands to change the tempo in 1 BPM increments after getting close with the Tap Tempo.

**Comment by talaviram** [comment]
You got it.
It'll be available in the next release. Up/Down keys.

**Comment by danryker** [comment]
Awesome! Thanks. 

How do I know when the release comes out? I don’t see a ‘check for updates’ option or an ‘update automatically’ option in the app.

Dan Ryker
www.danryker.com // 541-231-0897



On Sep 28, 2022, at 10:54 PM, Tal Aviram ***@***.***> wrote:


You got it.
It'll be available in the next release. Up/Down keys.

**Comment by talaviram** [comment]
Hey Dan, just a follow up, this is now available with 0.6.0 - 
https://github.com/talaviram/TICK/releases/tag/v0.6.0
